### ISSUE TITLE
Sensitivity to range limit occupancy

### ISSUE THREAD

**Issue by willvieira** [willvieira/STM-managed#3]
A quick test to define the best value of `occup` of the `range_limit()` function. This argument determines the threshold to define the range limit of a forest state. It determines the minimum occupancy a row of the landscape must be occupied by a specific forest state to be considered part of the state distribution.

Variables:
Occupancy: `0.7`, `0.75`, `0.8`, `0.85`, `0.9`, `0.95` %
Cell size: `0.5`, `0.8`, `1`, `2.5` Km

We will have `6` x `4` = `24` simulations x `15` replications with a different `initial_landscape`.

**Comment by willvieira** [comment]
First I calculated the south range limit of boreal and the north range limit of temperate for each `occup` value defined above, and then plotted it for each of the four sizes of cell.

Figure 1 shows how the range limit changed over time for each occupancy and cell size:

![rangeLimit_rangeLimit](https://user-images.githubusercontent.com/20832638/57109763-52ebe980-6d04-11e9-907d-37fcfc6e258f.png)

Instead of showing the position of the range limit of each time step as in figure 1, here I plot the distance travelled of the range limit for each time step (in Km/year). So for each time step, the distance travelled is calculated by (rangeLimit_position(t + 1) - rangeLimit_position(t)) * cellSize.

![migrationDist_rangeLimit](https://user-images.githubusercontent.com/20832638/57109766-54b5ad00-6d04-11e9-8915-988238dea6aa.png)

Figure 2 does not show much information about the different values of occupancy. In figure 3 I will calculate only the mean migration rate for the total simulation. So for each occupancy and cell size simulation, the mean migration rate is calculated by (rangeLimit_position(last time step) - rangeLimit_position(first time step)) * cellSize.

![migrationRate_rangeLimit](https://user-images.githubusercontent.com/20832638/57109770-567f7080-6d04-11e9-91d6-d5a07ce40214.png)

**Comment by willvieira** [comment]
It seems that the occupancy value has an effect only in the spatial position of the range limit (figure 1), but not really in the migration rate of the range limit (figure 3). Cell size has however a higher effect on migration rate (figure 3).

Although occupancy has a small effect, we see that higher values of `occup` will induce a smaller migration rate. And as we do not have any dispersion data to calibrate it, **I will choose the middle value of `occup = 0.85` for the simulations**.

**Comment by iboulangeat** [comment]
This is awsome. It means that dispersal distance (through the cell size effect) has an impact on boreal migration but not (or very few) on temperate migration. This is an excellent support for Steve results!
